config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/books')
  resources :books
  resources :levels
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :level
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    # @book.level_id = フォームからきたlevel_id
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
    puts params[:id]
  end

    # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :publisher, :memo, :level_id)
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def level_params
      params.require(:level).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, html: {class: 'form-horizontal', role: 'form'}) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: 'col-sm-1 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_field :title %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :author, class: 'col-sm-1 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_field :author %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :publisher, class: 'col-sm-1 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_field :publisher %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :memo, class: 'col-sm-1 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_area :memo %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :level_id, class: 'col-sm-1 control-label' %>
    <div class='col-sm-10'>
      <%= form.collection_select :level_id, Level.all, :id, :title %>
    </div>
  </div>

  <div class="actions">
    <div class='form-group'>
      <div class='col-sm-offset-1 col-sm-10'>
        <%= form.submit 'Submit',class: 'btn btn-success' %>
        <%= link_to 'Back', :back, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<!--<%#= link_to 'Show', @book %> |-->
<%#= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Memo</th>
      <th>Level</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book, class: 'widelink' %></td>
        <td><%= link_to book.author, book, class: 'widelink' %></td>
        <td><%= link_to book.publisher, book, class: 'widelink' %></td>
        <td><%= link_to book.memo, book, class: 'widelink' %></td>
        <td><%= link_to book.level.title, book, class: 'widelink' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path, class: 'btn btn-primary' %>　<%= link_to 'Show Levels', levels_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%#= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @book.memo %>
</p>

<p>
  <strong>Level:</strong>
  <%= @book.level.title %>
</p>
<%= link_to 'Delete',@book,
            method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger' %>
<%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary' %>
<%= link_to 'Back', books_path, class: 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- Fixed navbar -->
  <nav class='navbar navbar-inverse navbar-fixed-top'>
    <div class='container'>
      <div class='navbar-header'>
        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <%= link_to 'Learning Books', root_path, class: 'navbar-brand' %>
      </div>
      <div id='navbar' class='collapse navbar-collapse'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'Books', books_path %></li>
          <li><%= link_to 'Levels', levels_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/levels/_form.html.erb
<%= form_with(model: level, html: {class: 'form-horizontal', role: 'form'}) do |form| %>
  <% if level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
        <% level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: 'col-sm-1 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_field :title %>
    </div>
  </div>

  <div class="actions">
    <div class='form-group'>
      <div class='col-sm-offset-1 col-sm-10'>
        <%= form.submit 'Submit',class: 'btn btn-success' %>
        <%= link_to 'Back', :back, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form', level: @level %>

<!--<%#= link_to 'Show', @level %> |-->

<%#= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Levels</h1>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= link_to level.title, level, class: 'widelink' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path, class: 'btn btn-primary' %> <%= link_to 'Show Books', books_path %>

app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form', level: @level %>

<%#= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @level.title %>
</p>

<%= link_to 'Delete',@level,
            method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger' %>
<%= link_to 'Edit', edit_level_path(@level), class: 'btn btn-primary' %>
<%= link_to 'Back', levels_path, class: 'btn btn-default' %>